SELECT CURDATE();

SELECT CURTIME();

SELECT NOW();

SELECT YEAR(NOW());

SELECT MONTH(NOW());

SELECT DAY(NOW());

SELECT DATE_ADD(NOW(), INTERVAL 100 DAY);

SELECT DATEDIFF(CURDATE(), '2000-04-11');

SELECT name, DATEDIFF(CURDATE(), entry_date) AS 'days_of_entry' FROM employee ORDER BY days_of_entry DESC;