SHOW DATABASES;

-- CREATE DATABASE test;
CREATE DATABASE IF NOT EXISTS test;

CREATE DATABASE FOO DEFAULT CHARSET utf8mb4;

-- DROP DATABASE FOO;
DROP DATABASE IF EXISTS FOO;

USE test;

SELECT DATABASE();